# -*- coding: utf-8 -*-
"""Perceptrón Vs Redes Neuronales Multicapa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywA_Z2eHfO6D-9LXR3ZIHgnELc4jLTf7
"""



# ============================================================================
# PERCEPTRON vs MLP - CLASIFICACION MULTICLASE EN IRIS
# ============================================================================
# Este notebook implementa paso a paso la comparacion entre un Perceptron
# simple y una MLP (Multilayer Perceptron) para clasificar el dataset Iris.
# ============================================================================

# ----------------------------------------------------------------------------
# INSTALACION Y CONFIGURACION INICIAL
# ----------------------------------------------------------------------------

# Importamos todas las librerias necesarias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import warnings
warnings.filterwarnings('ignore')

# Configuracion para mejorar la visualizacion
plt.style.use('default')
sns.set_palette("husl")
np.random.seed(42)
tf.random.set_seed(42)

# Limpiar cualquier sesion anterior de Keras
keras.backend.clear_session()

print("=" * 80)
print("PERCEPTRON vs MLP - CLASIFICACION DEL DATASET IRIS")
print("=" * 80)
print("\nLibrerias importadas correctamente")
print("Semillas fijadas para reproducibilidad")
print("Sesion de Keras limpiada")

# ============================================================================
# PUNTO 1: CARGAR Y EXPLORAR EL DATASET
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 1: CARGAR Y EXPLORAR EL DATASET")
print("=" * 80)

# Cargar el dataset Iris
iris = load_iris()
X, y = iris.data, iris.target

# Crear un DataFrame para mejor visualizacion
df_iris = pd.DataFrame(X, columns=iris.feature_names)
df_iris['especie'] = pd.Categorical.from_codes(y, iris.target_names)

print("\nPRIMERAS 5 FILAS DEL DATASET:")
print(df_iris.head())

print("\nINFORMACION DEL DATASET:")
print(f"Numero total de muestras: {X.shape[0]}")
print(f"Numero de caracteristicas: {X.shape[1]}")
print(f"Nombres de las caracteristicas: {iris.feature_names}")
print(f"Numero de clases: {len(np.unique(y))}")
print(f"Nombres de las clases: {iris.target_names}")

print("\nESTADISTICAS DESCRIPTIVAS:")
print(df_iris.describe())

print("\nDISTRIBUCION DE CLASES:")
print(df_iris['especie'].value_counts())

# Visualizacion exploratoria
fig, axes = plt.subplots(2, 2, figsize=(12, 10))
fig.suptitle('PUNTO 1: Exploracion del Dataset Iris', fontsize=14, fontweight='bold')

# Grafico de dispersion para dos caracteristicas
colores = {'setosa': 'red', 'versicolor': 'blue', 'virginica': 'green'}
for i, especie in enumerate(iris.target_names):
    subset = df_iris[df_iris['especie'] == especie]
    axes[0,0].scatter(subset['sepal length (cm)'], subset['sepal width (cm)'],
                     label=especie, color=colores[especie], alpha=0.7)
axes[0,0].set_xlabel('Largo sepalo (cm)')
axes[0,0].set_ylabel('Ancho sepalo (cm)')
axes[0,0].set_title('Sepalo: Largo vs Ancho')
axes[0,0].legend()
axes[0,0].grid(True, alpha=0.3)

# Segundo grafico de dispersion
for i, especie in enumerate(iris.target_names):
    subset = df_iris[df_iris['especie'] == especie]
    axes[0,1].scatter(subset['petal length (cm)'], subset['petal width (cm)'],
                     label=especie, color=colores[especie], alpha=0.7)
axes[0,1].set_xlabel('Largo petalo (cm)')
axes[0,1].set_ylabel('Ancho petalo (cm)')
axes[0,1].set_title('Petalo: Largo vs Ancho')
axes[0,1].legend()
axes[0,1].grid(True, alpha=0.3)

# Boxplots para cada caracteristica
df_iris.boxplot(column=iris.feature_names[0], by='especie', ax=axes[1,0])
axes[1,0].set_title(f'Distribucion de {iris.feature_names[0]}')
axes[1,0].set_xlabel('Especie')

df_iris.boxplot(column=iris.feature_names[2], by='especie', ax=axes[1,1])
axes[1,1].set_title(f'Distribucion de {iris.feature_names[2]}')
axes[1,1].set_xlabel('Especie')

plt.tight_layout()
plt.show()

print("\nPUNTO 1 COMPLETADO: Dataset cargado y explorado")

# ============================================================================
# PUNTO 2: DIVIDIR EN ENTRENAMIENTO Y PRUEBA
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 2: DIVIDIR EN ENTRENAMIENTO Y PRUEBA")
print("=" * 80)

# Dividimos los datos: 70% entrenamiento, 30% prueba
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

print(f"\nDISTRIBUCION DE LAS PARTICIONES:")
print(f"Total de muestras: {len(X)}")
print(f"Muestras de entrenamiento: {len(X_train)} ({len(X_train)/len(X)*100:.1f}%)")
print(f"Muestras de prueba: {len(X_test)} ({len(X_test)/len(X)*100:.1f}%)")

print(f"\nDISTRIBUCION DE CLASES EN ENTRENAMIENTO:")
train_dist = pd.Series(y_train).value_counts().sort_index()
for i, count in enumerate(train_dist):
    print(f"  {iris.target_names[i]}: {count} muestras ({count/len(y_train)*100:.1f}%)")

print(f"\nDISTRIBUCION DE CLASES EN PRUEBA:")
test_dist = pd.Series(y_test).value_counts().sort_index()
for i, count in enumerate(test_dist):
    print(f"  {iris.target_names[i]}: {count} muestras ({count/len(y_test)*100:.1f}%)")

print("\nPUNTO 2 COMPLETADO: Datos divididos correctamente")

# ============================================================================
# PUNTO 3: NORMALIZAR LOS DATOS
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 3: NORMALIZAR LOS DATOS (STANDARDIZATION)")
print("=" * 80)

# Creamos el scaler y normalizamos los datos
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\nCOMPARACION ANTES Y DESPUES DE NORMALIZAR:")
print("\nPRIMERA MUESTRA DE ENTRENAMIENTO (valores originales):")
print(f"  {X_train[0]}")
print("\nPRIMERA MUESTRA DE ENTRENAMIENTO (normalizada - media=0, std=1):")
print(f"  {X_train_scaled[0]}")

print(f"\nESTADISTICAS DE LOS DATOS NORMALIZADOS:")
print(f"Media de caracteristicas normalizadas: {np.mean(X_train_scaled, axis=0).round(2)}")
print(f"Desviacion estandar: {np.std(X_train_scaled, axis=0).round(2)}")

# Convertir etiquetas a one-hot encoding para Keras
y_train_cat = keras.utils.to_categorical(y_train, 3)
y_test_cat = keras.utils.to_categorical(y_test, 3)

print(f"\nONE-HOT ENCODING:")
print(f"Etiqueta original (primera muestra): {y_train[0]}")
print(f"One-hot encoding: {y_train_cat[0]}")

print("\nPUNTO 3 COMPLETADO: Datos normalizados correctamente")

# ============================================================================
# PUNTO 4: IMPLEMENTAR UN MODELO PERCEPTRON (UNA SOLA CAPA)
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 4: IMPLEMENTAR PERCEPTRON (UNA CAPA, SIN CAPAS OCULTAS)")
print("=" * 80)

# Crear el modelo Perceptron
perceptron = keras.Sequential([
    layers.Dense(3,  # 3 neuronas de salida (una por clase)
                activation='softmax',  # Softmax para clasificacion multiclase
                input_shape=(4,),  # 4 caracteristicas de entrada
                name='capa_salida_perceptron')
], name='Perceptron_Iris')

print("\nARQUITECTURA DEL PERCEPTRON:")
perceptron.summary()

print("\nEXPLICACION DEL PERCEPTRON:")
print("- Una sola capa con 3 neuronas (una por clase)")
print("- Activacion softmax: convierte salidas en probabilidades")
print("- Formula: P(clase i|x) = exp(W_i·x + b_i) / Σ exp(W_j·x + b_j)")
print(f"- Parametros entrenables: {perceptron.count_params()}")
print("  - Pesos (W): 4 caracteristicas × 3 clases = 12 parametros")
print("  - Sesgos (b): 3 parametros")
print("- Limitacion: Solo puede aprender relaciones lineales")

# Compilar el perceptron
perceptron.compile(
    optimizer=keras.optimizers.SGD(learning_rate=0.01),  # SGD con lr=0.01
    loss='categorical_crossentropy',  # Cross-entropy para clasificacion
    metrics=['accuracy']
)

print("\nCONFIGURACION DEL ENTRENAMIENTO:")
print("- Optimizador: SGD (Stochastic Gradient Descent) con lr=0.01")
print("- Funcion de perdida: Categorical Cross-Entropy")
print("- Metrica de evaluacion: Accuracy")

print("\nPUNTO 4 COMPLETADO: Perceptron implementado")

# ============================================================================
# PUNTO 5: ENTRENAR Y EVALUAR EL PERCEPTRON
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 5: ENTRENAR Y EVALUAR EL PERCEPTRON")
print("=" * 80)

# Entrenar el perceptron
print("\nENTRENANDO PERCEPTRON (100 epocas)...")
historia_p = perceptron.fit(
    X_train_scaled, y_train_cat,
    epochs=100,
    batch_size=16,
    validation_split=0.1,  # 10% para validacion durante entrenamiento
    verbose=1
)

print("\nEVALUACION DEL PERCEPTRON EN DATOS DE PRUEBA:")
loss_p, acc_p = perceptron.evaluate(X_test_scaled, y_test_cat, verbose=0)
print(f"Loss (Cross-Entropy) en test: {loss_p:.4f}")
print(f"Accuracy en test: {acc_p*100:.2f}% ({int(acc_p*30)}/30 muestras correctas)")

# Predicciones del perceptron
y_pred_p = np.argmax(perceptron.predict(X_test_scaled, verbose=0), axis=1)

print("\nREPORTE DE CLASIFICACION - PERCEPTRON:")
print(classification_report(y_test, y_pred_p, target_names=iris.target_names))

print("\nINTERPRETACION DE METRICAS:")
print("- Precision: De las muestras que el modelo clasifico como X, cuantas realmente lo son?")
print("- Recall: De las muestras que realmente son X, cuantas detecto correctamente?")
print("- F1-score: Media armonica de precision y recall")

# Matriz de confusion del perceptron
cm_p = confusion_matrix(y_test, y_pred_p)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_p, annot=True, fmt='d', cmap='Reds',
            xticklabels=iris.target_names,
            yticklabels=iris.target_names,
            linewidths=2, linecolor='black',
            annot_kws={'size': 14, 'weight': 'bold'})
plt.title(f'PUNTO 5: Matriz de Confusion - Perceptron\nAccuracy: {acc_p*100:.2f}%',
          fontweight='bold', fontsize=12)
plt.xlabel('CLASE PREDICHA', fontsize=11)
plt.ylabel('CLASE REAL', fontsize=11)
plt.tight_layout()
plt.show()

print("\nPUNTO 5 COMPLETADO: Perceptron evaluado")

# ============================================================================
# PUNTO 6: IMPLEMENTAR MLP CON CAPA OCULTA (ReLU)
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 6: IMPLEMENTAR MLP (MULTILAYER PERCEPTRON) CON CAPA OCULTA")
print("=" * 80)

# Crear la MLP con una capa oculta
mlp = keras.Sequential([
    layers.Dense(8,  # Capa oculta con 8 neuronas
                activation='relu',  # ReLU para no linealidad
                input_shape=(4,),
                name='capa_oculta_1'),
    layers.Dense(3,  # Capa de salida con 3 neuronas
                activation='softmax',
                name='capa_salida_mlp')
], name='MLP_Iris_1capa')

print("\nARQUITECTURA DE LA MLP:")
mlp.summary()

print("\nEXPLICACION DE LA MLP:")
print("- Capa oculta: 8 neuronas con activacion ReLU")
print("  ReLU(x) = max(0, x) - introduce no linealidad")
print("- Capa de salida: 3 neuronas con softmax")
print(f"- Parametros entrenables: {mlp.count_params()}")
print("  - Capa oculta: (4x8 + 8) = 40 parametros")
print("  - Capa salida: (8x3 + 3) = 27 parametros")
print("  - Total: 67 parametros")
print("- Ventaja: Puede aprender relaciones NO lineales")

print("\nPUNTO 6 COMPLETADO: MLP implementada")

# ============================================================================
# PUNTO 7: DEFINIR FUNCION DE PERDIDA Y OPTIMIZADOR
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 7: DEFINIR FUNCION DE PERDIDA Y OPTIMIZADOR")
print("=" * 80)

# Compilar la MLP
mlp.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.01),  # Adam optimizer
    loss='categorical_crossentropy',  # Misma loss que el perceptron
    metrics=['accuracy']
)

print("\nFUNCION DE PERDIDA: CROSS-ENTROPY")
print("   L = -Σ y_i · log(ŷ_i)")
print("   - y_i: etiqueta real (0 o 1 en one-hot)")
print("   - ŷ_i: probabilidad predicha")
print("   - Penaliza mas las predicciones confiadas pero incorrectas")

print("\nOPTIMIZADOR: ADAM (Adaptive Moment Estimation)")
print("   - Combina ventajas de SGD con momentum y RMSprop")
print("   - Adapta la tasa de aprendizaje para cada parametro")
print("   - Generalmente converge mas rapido que SGD")
print("\n   Hiperparametros de Adam:")
print("   - learning_rate = 0.01 (tasa de aprendizaje inicial)")
print("   - beta_1 = 0.9 (decaimiento del momentum)")
print("   - beta_2 = 0.999 (decaimiento de la varianza)")
print("   - epsilon = 1e-7 (estabilidad numerica)")

print("\nPUNTO 7 COMPLETADO: Loss y optimizer configurados")

# ============================================================================
# PUNTO 8: ENTRENAR DURANTE MINIMO 50 EPOCAS
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 8: ENTRENAR MLP (MINIMO 50 EPOCAS)")
print("=" * 80)

# Entrenar la MLP
print("\nENTRENANDO MLP (100 epocas - supera minimo de 50)...")
historia_m = mlp.fit(
    X_train_scaled, y_train_cat,
    epochs=100,  # Superamos el minimo de 50
    batch_size=16,
    validation_split=0.1,
    verbose=1
)

print("\nEVOLUCION DEL ENTRENAMIENTO:")
print(f"Loss inicial: {historia_m.history['loss'][0]:.4f}")
print(f"Loss final: {historia_m.history['loss'][-1]:.4f}")
print(f"Reduccion de loss: {(historia_m.history['loss'][0] - historia_m.history['loss'][-1]):.4f}")
print(f"Accuracy inicial: {historia_m.history['accuracy'][0]*100:.2f}%")
print(f"Accuracy final: {historia_m.history['accuracy'][-1]*100:.2f}%")

print("\nPUNTO 8 COMPLETADO: MLP entrenada (100 epocas)")

# ============================================================================
# PUNTO 8 (continuacion): EVALUAR MLP
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 8 (continuacion): EVALUAR MLP EN TEST")
print("=" * 80)

print("\nEVALUACION DE LA MLP EN DATOS DE PRUEBA:")
loss_m, acc_m = mlp.evaluate(X_test_scaled, y_test_cat, verbose=0)
print(f"Loss (Cross-Entropy) en test: {loss_m:.4f}")
print(f"Accuracy en test: {acc_m*100:.2f}% ({int(acc_m*30)}/30 muestras correctas)")

# Predicciones de la MLP
y_pred_m = np.argmax(mlp.predict(X_test_scaled, verbose=0), axis=1)

print("\nREPORTE DE CLASIFICACION - MLP:")
print(classification_report(y_test, y_pred_m, target_names=iris.target_names))

# Matriz de confusion de la MLP
cm_m = confusion_matrix(y_test, y_pred_m)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_m, annot=True, fmt='d', cmap='Blues',
            xticklabels=iris.target_names,
            yticklabels=iris.target_names,
            linewidths=2, linecolor='black',
            annot_kws={'size': 14, 'weight': 'bold'})
plt.title(f'PUNTO 8: Matriz de Confusion - MLP\nAccuracy: {acc_m*100:.2f}%',
          fontweight='bold', fontsize=12)
plt.xlabel('CLASE PREDICHA', fontsize=11)
plt.ylabel('CLASE REAL', fontsize=11)
plt.tight_layout()
plt.show()

print("\nPUNTO 8 COMPLETADO: MLP evaluada")

# ============================================================================
# PUNTO 9: GRAFICAR EVOLUCION DE LA PERDIDA Y PRECISION
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 9: GRAFICAR EVOLUCION DEL ENTRENAMIENTO")
print("=" * 80)

print("""
COMO INTERPRETAR LAS GRAFICAS:

- Loss (perdida) decreciente: El modelo esta aprendiendo (backpropagation funciona)
- Accuracy creciente: El modelo mejora su precision en cada epoca
- Train loss baja pero val loss sube: OVERFITTING (modelo memoriza)
- Ambas curvas se estancan: UNDERFITTING (modelo muy simple)
- Curvas muy oscilantes: Tasa de aprendizaje demasiado alta

Linea solida = Entrenamiento
Linea punteada = Validacion
""")

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('PUNTO 9: Evolucion del Entrenamiento - Perceptron vs MLP',
             fontsize=14, fontweight='bold', y=1.02)

epocas = range(1, 101)

# Perdida del Perceptron
axes[0,0].plot(epocas, historia_p.history['loss'],
               color='#E74C3C', linewidth=2.5, label='Train Loss')
axes[0,0].plot(epocas, historia_p.history['val_loss'],
               color='#E74C3C', linewidth=2, linestyle='--', alpha=0.7, label='Val Loss')
axes[0,0].fill_between(epocas, historia_p.history['loss'], historia_p.history['val_loss'],
                       alpha=0.1, color='#E74C3C')
axes[0,0].set_title('Perceptron: Perdida por Epoca\n' +
                    f'Final: Train={historia_p.history["loss"][-1]:.3f}, Val={historia_p.history["val_loss"][-1]:.3f}',
                    fontweight='bold')
axes[0,0].set_xlabel('Epoca')
axes[0,0].set_ylabel('Loss (Cross-Entropy)')
axes[0,0].legend()
axes[0,0].grid(alpha=0.3)

# Precision del Perceptron
axes[0,1].plot(epocas, [v*100 for v in historia_p.history['accuracy']],
               color='#3498DB', linewidth=2.5, label='Train Acc')
axes[0,1].plot(epocas, [v*100 for v in historia_p.history['val_accuracy']],
               color='#3498DB', linewidth=2, linestyle='--', alpha=0.7, label='Val Acc')
axes[0,1].axhline(y=acc_p*100, color='#2C3E50', linestyle=':',
                  linewidth=2, label=f'Test final: {acc_p*100:.1f}%')
axes[0,1].set_title(f'Perceptron: Precision por Epoca\nTest final: {acc_p*100:.2f}%',
                    fontweight='bold')
axes[0,1].set_xlabel('Epoca')
axes[0,1].set_ylabel('Precision (%)')
axes[0,1].set_ylim([0, 105])
axes[0,1].legend()
axes[0,1].grid(alpha=0.3)

# Perdida de la MLP
axes[1,0].plot(epocas, historia_m.history['loss'],
               color='#2ECC71', linewidth=2.5, label='Train Loss')
axes[1,0].plot(epocas, historia_m.history['val_loss'],
               color='#2ECC71', linewidth=2, linestyle='--', alpha=0.7, label='Val Loss')
axes[1,0].fill_between(epocas, historia_m.history['loss'], historia_m.history['val_loss'],
                       alpha=0.1, color='#2ECC71')
axes[1,0].set_title('MLP: Perdida por Epoca\n' +
                    f'Final: Train={historia_m.history["loss"][-1]:.3f}, Val={historia_m.history["val_loss"][-1]:.3f}',
                    fontweight='bold')
axes[1,0].set_xlabel('Epoca')
axes[1,0].set_ylabel('Loss (Cross-Entropy)')
axes[1,0].legend()
axes[1,0].grid(alpha=0.3)

# Precision de la MLP
axes[1,1].plot(epocas, [v*100 for v in historia_m.history['accuracy']],
               color='#9B59B6', linewidth=2.5, label='Train Acc')
axes[1,1].plot(epocas, [v*100 for v in historia_m.history['val_accuracy']],
               color='#9B59B6', linewidth=2, linestyle='--', alpha=0.7, label='Val Acc')
axes[1,1].axhline(y=acc_m*100, color='#2C3E50', linestyle=':',
                  linewidth=2, label=f'Test final: {acc_m*100:.1f}%')
axes[1,1].set_title(f'MLP: Precision por Epoca\nTest final: {acc_m*100:.2f}%',
                    fontweight='bold')
axes[1,1].set_xlabel('Epoca')
axes[1,1].set_ylabel('Precision (%)')
axes[1,1].set_ylim([0, 105])
axes[1,1].legend()
axes[1,1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

print("\nPUNTO 9 COMPLETADO: Graficas de evolucion generadas")

# ============================================================================
# PUNTO 10: COMPARAR RESULTADOS PERCEPTRON vs MLP
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 10: COMPARAR RESULTADOS - PERCEPTRON vs MLP")
print("=" * 80)

# Crear tabla comparativa
comparacion = pd.DataFrame({
    'Metrica': ['Loss (test)', 'Accuracy (test)', 'Muestras correctas',
                'Parametros totales', 'Tiempo de entrenamiento (estimado)',
                'Capas ocultas', 'Activacion oculta', 'Capacidad de aprender no linealidad'],
    'Perceptron': [f'{loss_p:.4f}', f'{acc_p*100:.2f}%', f'{int(acc_p*30)}/30',
                   '15', '~2 segundos', '0', 'Softmax (solo salida)', 'NO'],
    'MLP (1 capa)': [f'{loss_m:.4f}', f'{acc_m*100:.2f}%', f'{int(acc_m*30)}/30',
                     '67', '~3 segundos', '1', 'ReLU', 'SI']
})

print("\nTABLA COMPARATIVA:")
print(comparacion.to_string(index=False))

print("\nANALISIS DE RESULTADOS:")

# Comparar accuracies
if acc_m > acc_p:
    print("\nLa MLP supera al Perceptron en accuracy")
    mejora = ((acc_m - acc_p) / acc_p) * 100
    print(f"Mejora relativa: {mejora:.1f}%")
else:
    print("\nEl Perceptron tiene igual o mejor accuracy que la MLP")

# Comparar perdidas
if loss_m < loss_p:
    print("\nLa MLP tiene menor perdida (mejor calibracion de probabilidades)")
    print(f"Reduccion de loss: {loss_p - loss_m:.4f}")
else:
    print("\nEl Perceptron tiene menor perdida")

print("\nCONCLUSIONES:")
print("""
1. La MLP tiene MAS parametros que el Perceptron (67 vs 15)
   -> Mayor capacidad de aprendizaje pero mas riesgo de overfitting

2. La MLP puede aprender relaciones NO LINEALES gracias a ReLU
   -> Util si las clases no son linealmente separables

3. En el dataset Iris, las clases son CASI linealmente separables
   -> Por eso ambos modelos funcionan bien

4. La MLP suele converger MAS RAPIDO que el Perceptron
   -> Gracias a la no linealidad y mejor optimizador (Adam)
""")

print("\nPUNTO 10 COMPLETADO: Comparativa realizada")

# ============================================================================
# PUNTO 11: MODIFICAR HIPERPARAMETROS Y ANALIZAR CAMBIOS
# ============================================================================
print("\n" + "=" * 80)
print("PUNTO 11: MODIFICAR HIPERPARAMETROS Y ANALIZAR CAMBIOS")
print("=" * 80)

print("""
EXPERIMENTOS CON DIFERENTES CONFIGURACIONES:

Vamos a probar 4 variantes de la MLP:
   A) Original: 1 capa oculta (8 neuronas), Adam lr=0.01
   B) Mas neuronas: 1 capa (16 neuronas)
   C) Mas capas: 2 capas (8 y 5 neuronas)
   D) Diferente optimizador: SGD con momentum
""")

# Experimento A: Original (ya lo tenemos)
print("\nEXPERIMENTO A: MLP Original (1 capa, 8 neuronas, Adam)")
print(f"   Accuracy: {acc_m*100:.2f}%")

# Experimento B: Mas neuronas
print("\nEXPERIMENTO B: MLP con 16 neuronas en capa oculta")
mlp_b = keras.Sequential([
    layers.Dense(16, activation='relu', input_shape=(4,), name='capa_oculta_16'),
    layers.Dense(3, activation='softmax', name='capa_salida_16')
], name='MLP_16neuronas')

mlp_b.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print("   Entrenando...")
hist_b = mlp_b.fit(X_train_scaled, y_train_cat, epochs=50,
                   validation_split=0.1, verbose=0, batch_size=16)
loss_b, acc_b = mlp_b.evaluate(X_test_scaled, y_test_cat, verbose=0)
print(f"   Accuracy en test: {acc_b*100:.2f}%")

# Experimento C: Mas capas
print("\nEXPERIMENTO C: MLP con 2 capas ocultas (8 y 5 neuronas)")
mlp_c = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(4,), name='capa_oculta_1'),
    layers.Dense(5, activation='relu', name='capa_oculta_2'),
    layers.Dense(3, activation='softmax', name='capa_salida_2capas')
], name='MLP_2capas')

mlp_c.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print("   Entrenando...")
hist_c = mlp_c.fit(X_train_scaled, y_train_cat, epochs=50,
                   validation_split=0.1, verbose=0, batch_size=16)
loss_c, acc_c = mlp_c.evaluate(X_test_scaled, y_test_cat, verbose=0)
print(f"   Accuracy en test: {acc_c*100:.2f}%")

# Experimento D: SGD con momentum
print("\nEXPERIMENTO D: MLP Original pero con SGD+momentum")
mlp_d = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(4,), name='capa_oculta_sgd'),
    layers.Dense(3, activation='softmax', name='capa_salida_sgd')
], name='MLP_SGD')

mlp_d.compile(
    optimizer=keras.optimizers.SGD(learning_rate=0.01, momentum=0.9),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("   Entrenando...")
hist_d = mlp_d.fit(X_train_scaled, y_train_cat, epochs=50,
                   validation_split=0.1, verbose=0, batch_size=16)
loss_d, acc_d = mlp_d.evaluate(X_test_scaled, y_test_cat, verbose=0)
print(f"   Accuracy en test: {acc_d*100:.2f}%")

# Tabla comparativa de experimentos
experimentos = pd.DataFrame({
    'Configuracion': ['Original (8, Adam)', '16 neuronas', '2 capas (8-5)', 'SGD+momentum'],
    'Arquitectura': ['[8] -> 3', '[16] -> 3', '[8->5] -> 3', '[8] -> 3'],
    'Optimizador': ['Adam (lr=0.01)', 'Adam (lr=0.01)', 'Adam (lr=0.01)', 'SGD+momentum'],
    'Accuracy': [f'{acc_m*100:.2f}%', f'{acc_b*100:.2f}%', f'{acc_c*100:.2f}%', f'{acc_d*100:.2f}%'],
    'Parametros': ['67', '115', '40+?', '67']
})

print("\nCOMPARACION DE EXPERIMENTOS:")
print(experimentos.to_string(index=False))

print("\nANALISIS DE HIPERPARAMETROS:")

print("""
1. EFECTO DE MAS NEURONAS:
   - Aumenta capacidad del modelo
   - Puede causar overfitting si hay pocos datos
   - En Iris: mejora minima (ya era casi perfecto)

2. EFECTO DE MAS CAPAS:
   - Permite aprender jerarquias de caracteristicas
   - Mas parametros -> mas entrenamiento necesario
   - En Iris: puede ser excesivo (datos pequenos)

3. EFECTO DEL OPTIMIZADOR:
   - Adam: converge rapido, buen desempeno general
   - SGD+momentum: mas estable pero mas lento
   - En Iris: ambos funcionan bien

4. RECOMENDACIONES PARA IRIS:
   - Modelo simple es suficiente (las clases son separables)
   - MLP pequena (8-16 neuronas) evita overfitting
   - 50-100 epocas son suficientes
""")

# Grafica comparativa final
plt.figure(figsize=(10, 6))
modelos = ['Perceptron', 'MLP Original', 'MLP 16neuronas', 'MLP 2capas', 'MLP SGD']
accuracies = [acc_p*100, acc_m*100, acc_b*100, acc_c*100, acc_d*100]
colores = ['red', 'blue', 'green', 'purple', 'orange']

bars = plt.bar(modelos, accuracies, color=colores, alpha=0.7)
plt.ylabel('Accuracy (%)', fontsize=12)
plt.title('PUNTO 11: Comparacion de Accuracy por Modelo', fontweight='bold', fontsize=14)
plt.ylim([0, 105])

# Anadir etiquetas con los valores
for bar, acc in zip(bars, accuracies):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
             f'{acc:.1f}%', ha='center', va='bottom', fontweight='bold')

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

print("\nPUNTO 11 COMPLETADO: Analisis de hiperparametros finalizado")

# ============================================================================
# RESUMEN FINAL
# ============================================================================
print("\n" + "=" * 80)
print("PROYECTO COMPLETADO: PERCEPTRON vs MLP EN IRIS")
print("=" * 80)

print("""
RESUMEN DE LO APRENDIDO:

PUNTO 1: Exploramos el dataset Iris (4 caracteristicas, 3 clases, 150 muestras)
PUNTO 2: Dividimos en 70% entrenamiento, 30% prueba
PUNTO 3: Normalizamos los datos (media=0, desviacion=1)
PUNTO 4: Implementamos Perceptron (una capa, softmax, 15 parametros)
PUNTO 5: Entrenamos y evaluamos Perceptron (accuracy ~{:.1f}%)
PUNTO 6: Implementamos MLP con capa oculta ReLU (8 neuronas)
PUNTO 7: Configuramos cross-entropy + Adam
PUNTO 8: Entrenamos MLP (100 epocas, accuracy ~{:.1f}%)
PUNTO 9: Graficamos evolucion de perdida y precision
PUNTO 10: Comparamos resultados (MLP supera ligeramente al Perceptron)
PUNTO 11: Experimentamos con hiperparametros (mas neuronas, mas capas, SGD)

CONCLUSION PRINCIPAL:
   Para el dataset Iris, ambos modelos funcionan bien porque las clases
   son casi linealmente separables. La MLP tiene ligera ventaja gracias
   a su capacidad no lineal, pero el Perceptron es mas simple y rapido.
""".format(acc_p*100, acc_m*100))

print("\n" + "=" * 80)
print("EJECUCION COMPLETA Y EXITOSA")
print("=" * 80)